name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install shell tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check .

      - name: Isort
        run: isort --check-only .

      - name: Mypy
        run: mypy src

      - name: Pytest
        run: pytest -q --cov=src --cov-report=term-missing

      - name: ShellCheck
        run: |
          set -euo pipefail
          if git ls-files -z '*.sh' | grep -qz .; then
            git ls-files -z '*.sh' | xargs -0 shellcheck
          else
            echo "No shell scripts to lint"
          fi

      - name: shfmt
        run: |
          set -euo pipefail
          if git ls-files -z '*.sh' | grep -qz .; then
            git ls-files -z '*.sh' | xargs -0 shfmt -d -i 4 -ci -sr
          else
            echo "No shell scripts to format"
          fi
